config/routes.rb
PersonalWebsite::Application.routes.draw do

  root :to => 'static#blog'
  match '/work', :to => "static#work", :as => :work
  match '/projects', :to => "static#projects", :as => :projects
  match '/about', :to => "static#about", :as => :about
  match '/contact', :to => "static#contact", :as => :contact
  match '/projects/artstudi_170_final_project', :to => "static#artstudi_170_final_project", :as => :artstudi_170_final_project

end

app/models/static.rb
class Static < ActiveRecord::Base
  attr_accessible :numLikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  config.relative_url_root = ""
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def blog
		if (params.count == 2) then
			@newer = false;
		else 
			@newer = true;
		end

		# @last_blog_post;
		# if (params[params.count] == @last_blog_post) then
		# 	@older = false;
		# else
		# 	@older = true;
		# end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_blog_template.html.erb
<!-- <div id="left_bar">
	<table id="left_table_bar">
			<tr>
				<td>
					<%= link_to root_path do%><div class="entry_date"><span class="date">Dec<br>2013</br></span><span class="number">19</span></div>
					<% end %>
				</td>
			</tr>
			<tr>
				<td>
					<a href="#"><div class="entry_date"><span class="date">Dec<br>2013</br></span><span class="number">1</span></div></a>
				</td>
			</tr>
			<tr>
				<td>
					<%= link_to :controller => "static", :action => "blog", :id => "bp11192013"  do%><div class="entry_date"><span class="date">Nov<br>2013</br></span><span class="number">19</span></div>
					<%end %>
				</td>
			</tr>
			<tr>
				<td>
					<a href="#"><div class="entry_date"><span class="date">Sep<br>2013</br></span><span class="number">12</span></div></a>
				</td>
			</tr>
			<tr>
				<td>
					<a href="#"><div class="entry_date"><span class="date">Aug<br>2013</br></span><span class="number">19</span></div></a>
				</td>
			</tr>
		</table>
</div> -->

<div id="social_share">
	<center>
		<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
		<br>
		<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a>
		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
		</script>
	</center>

</div>

<!-- <div id="like", onclick="increment()">
	<%= image_tag("like_image.png", :id => "like_img") %>
	<center><div id="like_num"></div></center>
</div> -->

app/views/layouts/_footer.html.erb
<div id="footer">
    <div id="footer_block">
        <div id="social_icons">
            <%= link_to image_tag("facebook.png", height: 29), "https://www.facebook.com/jonjyan" %>
            &nbsp;
            <%= link_to image_tag("twitter.png", height: 29), "https://twitter.com/jonjyan" %>
            &nbsp;
            <%= link_to image_tag("linked.png", height: 32), "http://www.linkedin.com/pub/jonathan-yan/34/208/a74" %> 
        </div>
        <h5 id="footer_text">Copyright &copy; <%= Time.now.year %> Jonathan Yan</h5>

        
    </div> 
</div>

app/views/layouts/_nav_bar.html.erb
<div id="nav_bar">
	<center>
		<table id="nav_table">
			<tr>
				<td class="nav_item">
					<%= link_to "blog", root_path, :class => "navigation_link" %>
				</td>
				<!-- <td class="nav_item">
					<%= link_to "work", work_path, :class => "navigation_link" %>
				</td> -->
				<td class="nav_item">
					<%= link_to "projects", projects_path, :class => "navigation_link" %>
				</td>
				<td class="nav_item">
					<%= link_to "about", about_path, :class => "navigation_link" %>
				</td>
				<td class="nav_item">
					<%= link_to "contact", contact_path, :class => "navigation_link" %>
				</td>
			</tr>
		</table>
	</center>
</div>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Jonathan Yan</title>
  <%= stylesheet_link_tag "main", :media => "all" %>
  <link rel="SHORTCUT ICON" href="favicon2.ico" />
  <%= javascript_include_tag "application" %>
  <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>

  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Montserrat">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:100">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:700">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:900">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:100">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:300">

  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Minion+Pro">

   <meta name="viewport" content="width=device-width, initial-scale=.33, maximum-scale=.33, user-scalable=0"/> <!--320 -->


</head>
<body>
		<script>(function(d, s, id) {
  		var js, fjs = d.getElementsByTagName(s)[0];
  		if (d.getElementById(id)) return;
	  		js = d.createElement(s); js.id = id;
	  		js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
	  		fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));
		</script>
	<div id="container">
    <div id="logo_container"><a class="logo_image" href="#"></a></div>
    <!--<%= link_to image_tag("JY_Logo3.png", :id => "logo_image"), root_path %>-->

		<%= render "layouts/nav_bar" %>

		<div id="body">
			<%= yield %>
		</div>
		<center>
			<div class="clearfooter"></div>
			<%= render "layouts/footer" %>
		</center>
	</div> <!-- End Container -->
</body>
</html>